import numpy as np
r1 = list(map(int,input("Enter the value of row1: ").strip().split()))
r2 = list(map(int,input("Enter the value of row2: ").strip().split()))
r3 = list(map(int,input("Enter the value of row3: ").strip().split()))
arr = np.array([r1,r2,r3])
print(arr)
print("The sum of rows are: ")
print("row1 : %d"%(np.sum(arr[0,:])))
print("row2 : %d"%(np.sum(arr[1,:])))
print("row3 : %d"%(np.sum(arr[2,:])))
print("The sum of coumns are: ")
print("col1 : %d"%(np.sum(arr[:,0])))
print("col2 : %d"%(np.sum(arr[:,1])))
print("col3 : %d"%(np.sum(arr[:,2])))
print("\n")