import numpy as np
lst=list(map(float,input("Enter the values :").strip().split()))
arr=np.array(lst)
print(arr)
tup = tuple(map(float,input("Enter the values :").strip().split()))
arr2=np.array(tup)
print(arr2)
arr3=np.zeros((3,4))
print(arr3)
arr4=np.arange(0,20,5)
print(arr4)
print(arr3.reshape(2,2,3))
arr=np.array([[ 0, 1, 2, 3, 4],[ 5, 6, 7, 8, 9],[10, 11, 12, 13, 14]])
print("maximum %d  and minimum %d element of array"%(np.max(arr),np.min(arr)))
print("Row1 max is %d  and min is %d, column1 max is %d and min is %d"%(np.max(arr[0,:]),np.min(arr[0,:]),np.max(arr[:,0]),np.min(arr[:,0])))
print("Row2 max is %d  and min is %d, column2 max is %d and min is %d"%(np.max(arr[1,:]),np.min(arr[1,:]),np.max(arr[:,1]),np.min(arr[:,1])))
print("Row2 max is %d  and min is %d, column3 max is %d and min is %d"%(np.max(arr[2,:]),np.min(arr[2,:]),np.max(arr[:,2]),np.min(arr[:,2])))
print("Sum of elements %d "%(np.sum(arr)))